#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=download-ssv2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Get username from $HOME
USERNAME=$(basename "$HOME")
REPO_DIR="/scratch-shared/$USERNAME/AdaWorld"

cd "$REPO_DIR"

conda activate download_data

bash data_download/something_something_v2/download_with_wget.sh
